import 'package:flutter_test/flutter_test.dart';
import 'package:heartry/database/database.dart';

import 'package:moor_generator/api/migrations.dart';

// The generated directory from before.
import '../generated/schema.dart';

void main() {
  late SchemaVerifier verifier;

  setUpAll(() {
    // GeneratedHelper() was generated by moor, the verifier is an api
    // provided by moor_generator.
    verifier = SchemaVerifier(GeneratedHelper());
  });

  test('upgrade from v1 to v2', () async {
    // Use startAt(1) to obtain a database connection with all tables
    // from the v1 schema.
    final connection = await verifier.startAt(1);
    final db = Database.connect(connection);

    // Use this to run a migration to v2 and then validate that the
    // database has the expected schema.
    await verifier.migrateAndValidate(db, 2);
  });
}
