targets:
  $default:
    builders:
      drift_dev|drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              modules:
                - fts5
          databases:
            poem: lib/database/database.dart
        generate_for:
          - "**/database/**"
      json_serializable|json_serializable:
        generate_for:
          - "**/models/**"
