name: heartry
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.0+17

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_icon_button: ^1.0.2
  animations: ^2.0.7
  badges: ^3.1.1
  catcher: ^0.7.0
  drift: ^2.4.0
  flex_color_picker: ^3.0.0
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.1.3
  get_it: ^7.2.0
  image_picker: ^1.0.0
  liquid_swipe: ^3.0.0
  package_info_plus: ^4.0.2
  path: ^1.8.1
  path_provider: ^2.0.8
  screenshot: ^2.1.0
  share_plus: ^7.0.2
  shared_preferences: ^2.0.12
  sqlite3_flutter_libs: ^0.5.3
  url_launcher: ^6.0.18
  flutter_staggered_grid_view: ^0.6.0
  dynamic_color: ^1.6.2
  http: ^1.1.0

dev_dependencies:
  build_runner: null
  drift_dev: ^2.4.0
  flutter_native_splash: ^2.2.16
  flutter_lints: ^2.0.1
  riverpod_lint: ^1.3.0

dependency_overrides:
  catcher:
    git:
      url: https://github.com/ThexXTURBOXx/catcher.git

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/launcher_icon.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Caveat-SemiBold.ttf
          weight: 600
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
